name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
            docker stop ${{ secrets.PROJECT_NAME }} || true
            docker rm ${{ secrets.PROJECT_NAME }} || true
            docker run -d -p 80:80 -p 443:443 --name ${{ secrets.PROJECT_NAME }} --restart unless-stopped \
              -e DOMAIN_NAME=${{ secrets.DOMAIN_NAME }} \
              -e EMAIL=${{ secrets.EMAIL }} \
              -e MAIN_APP_PORT=${{ secrets.MAIN_APP_PORT }} \
              -e CLOCK_APP_NAME=${{ secrets.CLOCK_APP_NAME }} \
              -e CLOCK_APP_PORT=${{ secrets.CLOCK_APP_PORT }} \
              -e CLOCK_APP_NAME=${{ secrets.AUTH_FORM_APP_NAME }} \
              -e CLOCK_APP_PORT=${{ secrets.AUTH_FORM_APP_PORT }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
            docker image prune -f
          EOF
